# Generated by Django 4.2.10 on 2024-03-01 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Логин должен состоять только из латинских букв, цифр и дефисов.', regex='[a-zA-Z0-9-]+')], verbose_name='Логин')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('password', models.CharField(validators=[django.core.validators.RegexValidator(message='Пароль должен содержать минимум 6 символов, одну заглавную букву, одну строчную букву и одну цифру.', regex='^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).{6,100}$')], verbose_name='Пароль')),
                ('countryCode', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Код страны должен состоять из 2 букв.', regex='[a-zA-Z]{2}')], verbose_name='Код страны')),
                ('isPublic', models.BooleanField(verbose_name='Публичный профиль')),
                ('phone', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен начинаться с + и состоять только из цифр.', regex='\\+[\\d]+')], verbose_name='Номер телефона')),
                ('image', models.CharField(default='', max_length=200, verbose_name='URL изображения')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
