# Generated by Django 4.2.10 on 2024-02-29 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alpha2', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]{2}')])),
                ('alpha3', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(regex='[a-zA-Z]{3}')])),
                ('region', models.TextField(validators=[django.core.validators.RegexValidator(regex='^(Europe|Africa|Americas|Oceania|Asia)$')])),
            ],
            options={
                'db_table': 'countries',
                'ordering': ('alpha2',),
                'managed': False,
            },
        ),
    ]
